services:
  # The Database
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: geodata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - ./data_postgis:/data/postgis_data

  # GeoServer
  geoserver:
    image: docker.osgeo.org/geoserver:2.28.0
    environment:
      INSTALL_EXTENSIONS: true
      STABLE_EXTENSIONS: vectortiles
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/geoserver_data
    depends_on:
      - db
